name = "notion-cloudflare-worker"
webpack_config = "webpack.config.js"
# Uncomment for pushing to a dev worker
#workers_dev = true

# Get these values from Cloudflare
account_id = ""
# This will be pushed as an env variable to Cloudflare.
# it is the cookie token_v2 for your user when accessing a notion doc
# This is how we access private docs
vars = { NOTION_TOKEN = "" }

# Production route
route = "firstround.cloud/*"
